# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' @export
MCG_Clayton_cpp <- function(time, status, theta) {
    .Call(`_RMSTdepC_MCG_Clayton_cpp`, time, status, theta)
}

MCG_Gumbel_cpp <- function(time, status, theta) {
    .Call(`_RMSTdepC_MCG_Gumbel_cpp`, time, status, theta)
}

MCG_Frank_cpp <- function(time, status, theta) {
    .Call(`_RMSTdepC_MCG_Frank_cpp`, time, status, theta)
}

MCG_cpp <- function(time, status, theta, family) {
    .Call(`_RMSTdepC_MCG_cpp`, time, status, family, theta)
}

sort_by <- function(x, y) {
    .Call(`_RMSTdepC_sort_by`, x, y)
}

SC_update_cpp <- function(time, status, Sx, Sy, family, theta, tol=1e-6) {
  .Call(`_RMSTdepC_SC_update_cpp`, time, status, Sx, Sy, family, theta, tol)
}

SC_copula_cpp <- function(time, status, family, theta, tol=1e-6) {
  .Call(`_RMSTdepC_SC_copula_cpp`, time, status, family, theta, tol)
}

RMST_cpp <- function(data, method, tau, theta, family, tol=1e-6) {
    .Call(`_RMSTdepC_RMST_cpp`, data, method, tau, family, theta, tol)
}

RMST_ENS_cpp <- function(data, method, tau, theta_vec=c(2.0/3.0,2.0,6.0), weight=c(1,1,1), tol=1e-6) {
    .Call(`_RMSTdepC_RMST_ENS_cpp`, data, method, tau, theta_vec, weight, tol)
}

RMST_var_cpp <- function(data, method, tau, family=3, theta=1, n_boots=999, ensemble=F, theta_vec=c(2.0/3.0,2.0,6.0), weight=c(1,1,1), tol=1e-6) {
    .Call(`_RMSTdepC_RMST_var_cpp`, data, method, tau, family, theta, n_boots, ensemble, theta_vec, weight, tol)
}
